# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Core partitioning function
#'
#' Computes the corresponding difference of a model combination with or without a variable (first one in the permutation). Written in C++.
#' @param perm One permutation of the variable numbers list
#' @model_ids A numeric vector with unique model id's
#' @gofs_vector A numeric vector with goodness-of-fit numbers
perm_cpp <- function(perm, model_ids, gofs_vector) {
    .Call('_ghp_perm_cpp', PACKAGE = 'ghp', perm, model_ids, gofs_vector)
}

