# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

perm_cpp <- function(perm, model_ids, gofs_vector) {
    .Call('_ghp_perm_cpp', PACKAGE = 'ghp', perm, model_ids, gofs_vector)
}

